apiVersion: apps/v1
kind: Deployment
metadata:
  name: itdo-erp-backend
  namespace: itdo-erp
  labels:
    app.kubernetes.io/name: itdo-erp-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/version: "2.0"
    app.kubernetes.io/managed-by: kubernetes
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: itdo-erp-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: itdo-erp-backend
        app.kubernetes.io/component: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      initContainers:
      - name: db-migration
        image: ghcr.io/itdojp/itdo_erp2-backend:latest
        imagePullPolicy: Always
        command: ["python", "-m", "alembic", "upgrade", "head"]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: itdo-erp-secrets
              key: DATABASE_URL
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: itdo-erp-secrets
              key: POSTGRES_PASSWORD
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      containers:
      - name: backend
        image: ghcr.io/itdojp/itdo_erp2-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: itdo-erp-secrets
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: itdo-erp-config
              key: REDIS_URL
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: itdo-erp-secrets
              key: SECRET_KEY
        - name: ENVIRONMENT
          value: "production"
        - name: DEBUG
          value: "false"
        - name: CORS_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: itdo-erp-config
              key: CORS_ORIGINS
        - name: API_PREFIX
          value: "/api/v1"
        - name: DOCS_URL
          value: null
        - name: REDOC_URL
          value: null
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: app-cache
          mountPath: /app/.cache
      volumes:
      - name: tmp
        emptyDir: {}
      - name: app-cache
        emptyDir: {}
      imagePullSecrets:
      - name: ghcr-secret