apiVersion: v1
kind: Service
metadata:
  name: itdo-erp-backend-service
  namespace: itdo-erp
  labels:
    app.kubernetes.io/name: itdo-erp-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/version: "2.0"
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: itdo-erp-backend
---
apiVersion: v1
kind: Service
metadata:
  name: itdo-erp-backend-headless
  namespace: itdo-erp
  labels:
    app.kubernetes.io/name: itdo-erp-backend
    app.kubernetes.io/component: backend
    service-type: headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: itdo-erp-backend