#!/bin/bash
# WSL上から実行可能なエージェント確認コマンド集

echo "================================================"
echo "Claude Code エージェント確認コマンド集"
echo "================================================"
echo ""
echo "# 1. 各エージェントの最新Issue活動を確認"
echo "gh issue list --label cc01 --state all --limit 5"
echo "gh issue list --label cc02 --state all --limit 5"
echo "gh issue list --label cc03 --state all --limit 5"
echo ""
echo "# 2. Issue #107（v2通知）の詳細確認"
echo "gh issue view 107 --comments"
echo ""
echo "# 3. PR #98の最新CI/CD状況"
echo "gh pr checks 98 | head -20"
echo ""
echo "# 4. Issue #99の最新5コメント確認"
echo "gh issue view 99 --comments | tail -50"
echo ""
echo "# 5. エージェントの状態ファイル確認（もし存在すれば）"
echo "ls -la ~/.claude-agent-state 2>/dev/null || echo '状態ファイルなし'"
echo ""
echo "# 6. バックグラウンドプロセス確認"
echo "ps aux | grep -E '(agent-work|sleep 900|claude)' | grep -v grep"
echo ""
echo "# 7. 最新のgitコミット確認（エージェント活動）"
echo "git log --oneline --author='Claude' --since='10 hours ago'"
echo ""
echo "# 8. エージェントへの追加指示送信例"
echo "# gh issue comment 107 --body 'CC02/CC03: 初期化状況を報告してください'"
echo ""
echo "================================================"
echo "これらのコマンドを実行して状況を確認してください"