# Prometheus Configuration for Development Environment
# Advanced monitoring with comprehensive metrics collection

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    monitor: 'itdo-dev-monitor'
    environment: 'development'

# Rule files
rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Scrape configurations
scrape_configs:
  # ============================================================================
  # Prometheus itself
  # ============================================================================
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # ============================================================================
  # Backend Application Metrics
  # ============================================================================
  - job_name: 'backend-app'
    static_configs:
      - targets: ['backend-dev:8000']
    scrape_interval: 5s
    metrics_path: '/metrics'
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']

  # ============================================================================
  # Database Metrics - PostgreSQL Exporter
  # ============================================================================
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 10s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: postgres-exporter:9187

  # ============================================================================
  # Redis Metrics - Redis Exporter
  # ============================================================================
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 10s
    metrics_path: /metrics

  # ============================================================================
  # Node.js Application Metrics (Frontend build process)
  # ============================================================================
  - job_name: 'nodejs-app'
    static_configs:
      - targets: ['frontend-dev:3001']
    scrape_interval: 15s
    metrics_path: '/metrics'
    honor_labels: true

  # ============================================================================
  # Nginx Metrics - High Performance Web Server
  # ============================================================================
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 10s
    metrics_path: /metrics

  # ============================================================================
  # Container Runtime Metrics - cAdvisor
  # ============================================================================
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 5s
    metrics_path: /metrics
    honor_labels: true

  # ============================================================================
  # Host System Metrics - Node Exporter
  # ============================================================================
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s
    metrics_path: /metrics

  # ============================================================================
  # Application Performance Monitoring - Custom Metrics
  # ============================================================================
  - job_name: 'custom-metrics'
    static_configs:
      - targets: ['backend-dev:8001']  # Custom metrics endpoint
    scrape_interval: 5s
    metrics_path: '/custom-metrics'
    honor_timestamps: true
    params:
      collect[]:
        - 'database_connections'
        - 'api_response_times'
        - 'user_sessions'
        - 'cache_hit_rates'
        - 'error_rates'

  # ============================================================================
  # Development Tools Monitoring
  # ============================================================================
  - job_name: 'dev-tools'
    static_configs:
      - targets: 
        - 'pgadmin-dev:80'
        - 'redis-commander:8081'
        - 'grafana-dev:3000'
    scrape_interval: 30s
    metrics_path: /metrics
    honor_labels: false

  # ============================================================================
  # API Endpoint Health Checks
  # ============================================================================
  - job_name: 'api-health'
    static_configs:
      - targets: ['backend-dev:8000']
    scrape_interval: 5s
    metrics_path: '/health'
    params:
      format: ['prometheus']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'api_health.*'
        target_label: service
        replacement: 'backend-api'

  # ============================================================================
  # Frontend Application Health
  # ============================================================================
  - job_name: 'frontend-health'
    static_configs:
      - targets: ['frontend-dev:3000']
    scrape_interval: 10s
    metrics_path: '/health'
    honor_labels: true

  # ============================================================================
  # Load Testing Metrics (when running performance tests)
  # ============================================================================
  - job_name: 'load-test'
    static_configs:
      - targets: ['locust-master:8089']
    scrape_interval: 5s
    metrics_path: '/stats/requests'
    honor_labels: true
    scrape_timeout: 10s

# Storage configuration for development
storage:
  tsdb:
    path: /prometheus
    retention.time: 7d
    retention.size: 10GB
    wal-compression: true
    min-block-duration: 2h
    max-block-duration: 25h

# Remote write configuration (optional - for centralized monitoring)
# remote_write:
#   - url: "https://monitoring.itdo.jp/api/v1/write"
#     basic_auth:
#       username: "dev-prometheus"
#       password: "dev-password"
#     queue_config:
#       capacity: 10000
#       max_shards: 200
#       min_shards: 1
#       max_samples_per_send: 2000
#       batch_send_deadline: 5s

# Remote read configuration
# remote_read:
#   - url: "https://monitoring.itdo.jp/api/v1/read"
#     basic_auth:
#       username: "dev-prometheus"
#       password: "dev-password"