apiVersion: v1
kind: Secret
metadata:
  name: itdo-erp-secrets
  namespace: itdo-erp
  labels:
    app.kubernetes.io/name: itdo-erp
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # Database credentials (base64 encoded)
  DATABASE_URL: cG9zdGdyZXNxbDovL2l0ZG9fZXJwOnNlY3VyZV9wYXNzd29yZF8yMDI1QHBvc3RncmVzLXNlcnZpY2UuaXRkby1lcnAtZGF0YS5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL2l0ZG9fZXJw  # postgresql://itdo_erp:secure_password_2025@postgres-service.itdo-erp-data.svc.cluster.local:5432/itdo_erp
  POSTGRES_PASSWORD: c2VjdXJlX3Bhc3N3b3JkXzIwMjU=  # secure_password_2025
  REDIS_PASSWORD: cmVkaXNfcGFzc3dvcmRfMjAyNQ==  # redis_password_2025
  
  # Application secrets
  SECRET_KEY: aXRkb19lcnBfc3VwZXJfc2VjcmV0X2tleV8yMDI1X3Byb2R1Y3Rpb24=  # itdo_erp_super_secret_key_2025_production
  
  # JWT secrets
  JWT_SECRET_KEY: and0X3NlY3JldF9rZXlfZm9yX2p3dF90b2tlbnNfMjAyNQ==  # jwt_secret_key_for_jwt_tokens_2025
  JWT_ALGORITHM: SFMyNTY=  # HS256
  
  # OAuth secrets (for Keycloak integration)
  OAUTH_CLIENT_SECRET: b2F1dGhfY2xpZW50X3NlY3JldF8yMDI1  # oauth_client_secret_2025
  
  # Email service secrets
  SMTP_PASSWORD: c210cF9wYXNzd29yZF8yMDI1  # smtp_password_2025
  
  # Encryption keys
  ENCRYPTION_KEY: ZW5jcnlwdGlvbl9rZXlfZm9yX3NlbnNpdGl2ZV9kYXRhXzIwMjU=  # encryption_key_for_sensitive_data_2025
---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: itdo-erp
  labels:
    app.kubernetes.io/name: itdo-erp
    app.kubernetes.io/component: registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiaXRkb2pwIiwicGFzc3dvcmQiOiJnaHBfdG9rZW5faGVyZSIsImF1dGgiOiJhWFJrYjJwd09taG9jRjkwYjJ0bGJsOW9aWEpsIn19fQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: itdo-erp-secrets
  namespace: itdo-erp-data
  labels:
    app.kubernetes.io/name: itdo-erp-data
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # Same secrets for data namespace
  POSTGRES_PASSWORD: c2VjdXJlX3Bhc3N3b3JkXzIwMjU=  # secure_password_2025
  REDIS_PASSWORD: cmVkaXNfcGFzc3dvcmRfMjAyNQ==  # redis_password_2025