# CC03 v62.0 - 7日間集中インフラスプリント
# Day 2: Alertmanager設定 (v0.26.0対応)

global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@itdo-erp-v62.com'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://localhost:5001/webhook'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname']