apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: itdo-erp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/itdojp/ITDO_ERP2
    targetRevision: HEAD
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: itdo-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true