---
# Redis High Availability - Master-Replica Configuration
# CC03 v68.0 Day 2: Enterprise Redis Cluster with Sentinel

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-master
  namespace: itdo-erp-production
  labels:
    app: redis
    role: master
    tier: cache
    version: "7.2.3"
spec:
  serviceName: redis-master-service
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: master
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: cache
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
      - name: redis-master
        image: redis:7.2.3-alpine
        command:
        - redis-server
        - /etc/redis/redis.conf
        - --masterauth
        - $(REDIS_PASSWORD)
        - --requirepass
        - $(REDIS_PASSWORD)
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secrets
              key: password
        - name: REDIS_REPLICATION_MODE
          value: master
        ports:
        - name: redis
          containerPort: 6379
          protocol: TCP
        volumeMounts:
        - name: redis-data
          mountPath: /data
        - name: redis-config
          mountPath: /etc/redis
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          exec:
            command:
            - redis-cli
            - --no-auth-warning
            - -a
            - $(REDIS_PASSWORD)
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - redis-cli
            - --no-auth-warning
            - -a
            - $(REDIS_PASSWORD)
            - ping
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
      volumes:
      - name: redis-config
        configMap:
          name: redis-master-config
  volumeClaimTemplates:
  - metadata:
      name: redis-data
      labels:
        app: redis
        role: master
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: fast-ssd
      resources:
        requests:
          storage: 20Gi

---
# Redis Replica Configuration
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-replica
  namespace: itdo-erp-production
  labels:
    app: redis
    role: replica
    tier: cache
    version: "7.2.3"
spec:
  serviceName: redis-replica-service
  replicas: 2
  selector:
    matchLabels:
      app: redis
      role: replica
  template:
    metadata:
      labels:
        app: redis
        role: replica
        tier: cache
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
      - name: redis-replica
        image: redis:7.2.3-alpine
        command:
        - redis-server
        - /etc/redis/redis.conf
        - --replicaof
        - redis-master-service
        - "6379"
        - --masterauth
        - $(REDIS_PASSWORD)
        - --requirepass
        - $(REDIS_PASSWORD)
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secrets
              key: password
        - name: REDIS_REPLICATION_MODE
          value: replica
        - name: REDIS_MASTER_HOST
          value: "redis-master-service"
        - name: REDIS_MASTER_PORT
          value: "6379"
        ports:
        - name: redis
          containerPort: 6379
          protocol: TCP
        volumeMounts:
        - name: redis-data
          mountPath: /data
        - name: redis-config
          mountPath: /etc/redis
        resources:
          requests:
            memory: "768Mi"
            cpu: "250m"
          limits:
            memory: "1.5Gi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - redis-cli
            - --no-auth-warning
            - -a
            - $(REDIS_PASSWORD)
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - redis-cli
            - --no-auth-warning
            - -a
            - $(REDIS_PASSWORD)
            - ping
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
      volumes:
      - name: redis-config
        configMap:
          name: redis-replica-config
  volumeClaimTemplates:
  - metadata:
      name: redis-data
      labels:
        app: redis
        role: replica
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: fast-ssd
      resources:
        requests:
          storage: 20Gi

---
# Redis Master Service
apiVersion: v1
kind: Service
metadata:
  name: redis-master-service
  namespace: itdo-erp-production
  labels:
    app: redis
    role: master
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: redis
    role: master

---
# Redis Replica Service (Read-only)
apiVersion: v1
kind: Service
metadata:
  name: redis-replica-service
  namespace: itdo-erp-production
  labels:
    app: redis
    role: replica
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: redis
    role: replica

---
# Redis Headless Service for Sentinel Discovery
apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: itdo-erp-production
  labels:
    app: redis
    component: headless
spec:
  clusterIP: None
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: redis

---
# Redis Secrets
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: itdo-erp-production
type: Opaque
stringData:
  password: "$(openssl rand -base64 32)"
  sentinel_password: "$(openssl rand -base64 32)"

---
# Redis Master Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-master-config
  namespace: itdo-erp-production
  labels:
    app: redis
    role: master
data:
  redis.conf: |
    # Basic Configuration
    port 6379
    bind 0.0.0.0
    protected-mode yes
    
    # Memory Management
    maxmemory 1gb
    maxmemory-policy allkeys-lru
    maxmemory-samples 5
    
    # Persistence Configuration
    save 900 1
    save 300 10
    save 60 10000
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes
    dbfilename redis-master.rdb
    dir /data
    
    # AOF Configuration
    appendonly yes
    appendfilename "redis-master.aof"
    appendfsync everysec
    no-appendfsync-on-rewrite no
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb
    aof-load-truncated yes
    aof-use-rdb-preamble yes
    
    # Replication Configuration
    replica-serve-stale-data yes
    replica-read-only no
    repl-diskless-sync yes
    repl-diskless-sync-delay 5
    repl-ping-replica-period 10
    repl-timeout 60
    repl-disable-tcp-nodelay no
    repl-backlog-size 1mb
    repl-backlog-ttl 3600
    
    # Security
    rename-command FLUSHDB ""
    rename-command FLUSHALL ""
    rename-command DEBUG ""
    rename-command CONFIG "CONFIG_8a3f5e2d9c4b"
    
    # Client Configuration
    timeout 300
    tcp-keepalive 60
    tcp-backlog 511
    
    # Performance Tuning
    databases 16
    hash-max-ziplist-entries 512
    hash-max-ziplist-value 64
    list-max-ziplist-size -2
    list-compress-depth 0
    set-max-intset-entries 512
    zset-max-ziplist-entries 128
    zset-max-ziplist-value 64
    hll-sparse-max-bytes 3000
    
    # Slow Log
    slowlog-log-slower-than 10000
    slowlog-max-len 128
    
    # Latency Monitoring
    latency-monitor-threshold 100
    
    # Notifications
    notify-keyspace-events ""
    
    # Advanced Memory
    activerehashing yes
    client-output-buffer-limit normal 0 0 0
    client-output-buffer-limit replica 256mb 64mb 60
    client-output-buffer-limit pubsub 32mb 8mb 60
    hz 10
    dynamic-hz yes
    
    # Logging
    loglevel notice
    logfile ""
    syslog-enabled no

---
# Redis Replica Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-replica-config
  namespace: itdo-erp-production
  labels:
    app: redis
    role: replica
data:
  redis.conf: |
    # Basic Configuration
    port 6379
    bind 0.0.0.0
    protected-mode yes
    
    # Memory Management (Smaller for replica)
    maxmemory 768mb
    maxmemory-policy allkeys-lru
    maxmemory-samples 5
    
    # Persistence Configuration (Reduced for replica)
    save 1800 1
    save 300 100
    save 60 10000
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes
    dbfilename redis-replica.rdb
    dir /data
    
    # AOF Configuration (Disabled for replica to save resources)
    appendonly no
    
    # Replica-specific Configuration
    replica-serve-stale-data yes
    replica-read-only yes
    replica-priority 100
    min-replicas-to-write 1
    min-replicas-max-lag 10
    
    # Replication Configuration
    repl-diskless-sync yes
    repl-diskless-sync-delay 5
    repl-ping-replica-period 10
    repl-timeout 60
    repl-disable-tcp-nodelay no
    repl-backlog-size 1mb
    repl-backlog-ttl 3600
    
    # Security
    rename-command FLUSHDB ""
    rename-command FLUSHALL ""
    rename-command DEBUG ""
    rename-command CONFIG "CONFIG_8a3f5e2d9c4b"
    
    # Client Configuration
    timeout 300
    tcp-keepalive 60
    tcp-backlog 511
    
    # Performance Tuning
    databases 16
    hash-max-ziplist-entries 512
    hash-max-ziplist-value 64
    list-max-ziplist-size -2
    list-compress-depth 0
    set-max-intset-entries 512
    zset-max-ziplist-entries 128
    zset-max-ziplist-value 64
    hll-sparse-max-bytes 3000
    
    # Slow Log (Reduced for replica)
    slowlog-log-slower-than 20000
    slowlog-max-len 64
    
    # Latency Monitoring
    latency-monitor-threshold 100
    
    # Advanced Memory
    activerehashing yes
    client-output-buffer-limit normal 0 0 0
    client-output-buffer-limit replica 256mb 64mb 60
    client-output-buffer-limit pubsub 32mb 8mb 60
    hz 10
    dynamic-hz yes
    
    # Logging (Reduced for replica)
    loglevel warning
    logfile ""
    syslog-enabled no

---
# Network Policy for Redis Security
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-network-policy
  namespace: itdo-erp-production
spec:
  podSelector:
    matchLabels:
      app: redis
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: itdo-erp-production
    - podSelector:
        matchLabels:
          tier: application
    - podSelector:
        matchLabels:
          app: redis-sentinel
    ports:
    - protocol: TCP
      port: 6379
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: redis
    ports:
    - protocol: TCP
      port: 6379
  - to: []
    ports:
    - protocol: UDP
      port: 53