{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "itdo-erp.fullname" . }}-frontend
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "itdo-erp.frontend.labels" . | nindent 4 }}
  {{- with .Values.frontend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  sessionAffinity: None
  ports:
  - name: http
    port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
    protocol: TCP
  selector:
    {{- include "itdo-erp.frontend.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "itdo-erp.fullname" . }}-frontend-headless
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "itdo-erp.frontend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: false
  ports:
  - name: http
    port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
    protocol: TCP
  selector:
    {{- include "itdo-erp.frontend.selectorLabels" . | nindent 4 }}
{{- end }}