apiVersion: v1
kind: Secret
metadata:
  name: {{ include "itdo-erp.fullname" . }}-secrets
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "itdo-erp.labels" . | nindent 4 }}
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # Database Credentials (base64 encoded)
  DATABASE_USER: {{ "itdo_erp_user" | b64enc }}
  DATABASE_PASSWORD: {{ "itdo_erp_pass" | b64enc }}
  
  # Redis Password
  REDIS_PASSWORD: {{ "redis_pass" | b64enc }}
  
  # JWT Secret Key
  JWT_SECRET_KEY: {{ "jwtSecretKey1234567890" | b64enc }}
  
  # API Keys
  OPENAI_API_KEY: {{ "sk-fake-openai-key" | b64enc }}
  STRIPE_SECRET_KEY: {{ "sk_fake_stripe_key" | b64enc }}
  
  # OAuth Secrets
  {{- if .Values.external.keycloak.enabled }}
  KEYCLOAK_CLIENT_SECRET: {{ .Values.external.keycloak.clientSecret | b64enc }}
  {{- else }}
  KEYCLOAK_CLIENT_SECRET: {{ "keycloak_client_secret" | b64enc }}
  {{- end }}
  GOOGLE_OAUTH_SECRET: {{ "google_oauth_secret" | b64enc }}
  
  # Encryption Keys
  ENCRYPTION_KEY: {{ "encryption_key_32_bytes_long" | b64enc }}
  
  # SMTP Credentials
  {{- if .Values.external.email.enabled }}
  SMTP_PASSWORD: {{ .Values.external.email.smtp.password | b64enc }}
  {{- else }}
  SMTP_PASSWORD: {{ "smtp_password" | b64enc }}
  {{- end }}
  
  # S3/Object Storage Credentials
  {{- if .Values.external.objectStorage.enabled }}
  AWS_ACCESS_KEY_ID: {{ .Values.external.objectStorage.accessKey | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.external.objectStorage.secretKey | b64enc }}
  {{- else }}
  AWS_ACCESS_KEY_ID: {{ "aws_access_key" | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ "aws_secret_access_key" | b64enc }}
  {{- end }}

---
{{- if .Values.ingress.enabled and .Values.ingress.tls }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "itdo-erp.fullname" . }}-tls
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "itdo-erp.labels" . | nindent 4 }}
    app.kubernetes.io/component: tls
type: kubernetes.io/tls
data:
  tls.crt: {{ "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=" }}
  tls.key: {{ "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=" }}
{{- end }}

---
{{- if .Values.global.imagePullSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "itdo-erp.fullname" . }}-registry
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "itdo-erp.labels" . | nindent 4 }}
    app.kubernetes.io/component: registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ "eyJhdXRocyI6eyJyZWdpc3RyeS5pdGRvLWVycC5jb20iOnsidXNlcm5hbWUiOiJpdGRvLWVycCIsInBhc3N3b3JkIjoicmVnaXN0cnlfcGFzcyIsImVtYWlsIjoiZGV2QGl0ZG8tZXJwLmNvbSIsImF1dGgiOiJhWFJrYnkxbGNuQTZjbVZuYVhOMGNubGZjR0Z6Y3c9PSJ9fX0=" }}
{{- end }}

---
{{- if .Values.monitoring.grafana.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "itdo-erp.fullname" . }}-grafana-admin
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "itdo-erp.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring
type: Opaque
data:
  admin-user: {{ "admin" | b64enc }}
  admin-password: {{ "admin_password_123" | b64enc }}
{{- end }}

---
{{- if .Values.certManager.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "itdo-erp.fullname" . }}-cloudflare-api-key
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "itdo-erp.labels" . | nindent 4 }}
    app.kubernetes.io/component: certificate-management
type: Opaque
data:
  api-key: {{ "fake_cloudflare_api_key" | b64enc }}
{{- end }}