apiVersion: v1
kind: Secret
metadata:
  name: itdo-erp-secrets
  namespace: itdo-erp
  labels:
    app.kubernetes.io/name: itdo-erp
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # Database Credentials (base64 encoded)
  DATABASE_USER: aXRkb19lcnBfdXNlcg== # itdo_erp_user
  DATABASE_PASSWORD: aXRkb19lcnBfcGFzcw== # itdo_erp_pass
  
  # Redis Password
  REDIS_PASSWORD: cmVkaXNfcGFzcw== # redis_pass
  
  # JWT Secret Key
  JWT_SECRET_KEY: anlTZWNyZXRLZXkxMjM0NTY3ODkw # jwtSecretKey1234567890
  
  # API Keys
  OPENAI_API_KEY: c2stZmFrZS1vcGVuYWkta2V5 # sk-fake-openai-key
  STRIPE_SECRET_KEY: c2tfZmFrZV9zdHJpcGVfa2V5 # sk_fake_stripe_key
  
  # OAuth Secrets
  KEYCLOAK_CLIENT_SECRET: a2V5Y2xvYWtfY2xpZW50X3NlY3JldA== # keycloak_client_secret
  GOOGLE_OAUTH_SECRET: Z29vZ2xlX29hdXRoX3NlY3JldA== # google_oauth_secret
  
  # Encryption Keys
  ENCRYPTION_KEY: ZW5jcnlwdGlvbl9rZXlfMzJfYnl0ZXNfbG9uZw== # encryption_key_32_bytes_long
  
  # SMTP Credentials
  SMTP_PASSWORD: c210cF9wYXNzd29yZA== # smtp_password
  
  # S3/Object Storage Credentials
  AWS_ACCESS_KEY_ID: YXdzX2FjY2Vzc19rZXk= # aws_access_key
  AWS_SECRET_ACCESS_KEY: YXdzX3NlY3JldF9hY2Nlc3Nfa2V5 # aws_secret_access_key
  
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: itdo-erp
  labels:
    app.kubernetes.io/name: itdo-erp
    app.kubernetes.io/component: tls
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0= # Base64 encoded certificate
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0= # Base64 encoded private key
  
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: itdo-erp
  labels:
    app.kubernetes.io/name: itdo-erp
    app.kubernetes.io/component: registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5pdGRvLWVycC5jb20iOnsidXNlcm5hbWUiOiJpdGRvLWVycCIsInBhc3N3b3JkIjoicmVnaXN0cnlfcGFzcyIsImVtYWlsIjoiZGV2QGl0ZG8tZXJwLmNvbSIsImF1dGgiOiJhWFJrYnkxbGNuQTZjbVZuYVhOMGNubGZjR0Z6Y3c9PSJ9fX0=