apiVersion: v1
kind: Service
metadata:
  name: itdo-erp-frontend-service
  namespace: itdo-erp
  labels:
    app.kubernetes.io/name: itdo-erp-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/version: "2.0"
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: itdo-erp-frontend
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: itdo-erp-frontend-hpa
  namespace: itdo-erp
  labels:
    app.kubernetes.io/name: itdo-erp-frontend
    app.kubernetes.io/component: autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: itdo-erp-frontend
  minReplicas: 3
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 15
      - type: Pods
        value: 2
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 120
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: itdo-erp-frontend-pdb
  namespace: itdo-erp
  labels:
    app.kubernetes.io/name: itdo-erp-frontend
    app.kubernetes.io/component: availability
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: itdo-erp-frontend