# ITDO ERP v2 - Production Secrets Template
# CC03 v48.0 Business-Aligned Infrastructure
# Note: This is a template. Real secrets should be managed via sealed-secrets or external secret management

apiVersion: v1
kind: Secret
metadata:
  name: itdo-erp-secrets
  namespace: itdo-erp-prod
  labels:
    app.kubernetes.io/name: itdo-erp
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # Database credentials (base64 encoded)
  POSTGRES_USER: aXRkb19lcnBfdXNlcg==  # itdo_erp_user
  POSTGRES_PASSWORD: c3VwZXJfc2VjdXJlX3Bhc3N3b3JkXzIwMjU=  # super_secure_password_2025
  DATABASE_URL: cG9zdGdyZXNxbDovL2l0ZG9fZXJwX3VzZXI6c3VwZXJfc2VjdXJlX3Bhc3N3b3JkXzIwMjVAcG9zdGdyZXNxbC1jbHVzdGVyLXNlcnZpY2UuaXRkby1lcnAtZGF0YS5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL2l0ZG9fZXJwX3Byb2Q=
  
  # Redis credentials
  REDIS_PASSWORD: cmVkaXNfc2VjdXJlX3Bhc3N3b3JkXzIwMjU=  # redis_secure_password_2025
  
  # JWT and Security
  SECRET_KEY: ZXh0cmVtZWx5X3NlY3VyZV9qd3Rfc2VjcmV0X2tleV9mb3JfcHJvZHVjdGlvbl8yMDI1X2l0ZG9fZXJw  # extremely_secure_jwt_secret_key_for_production_2025_itdo_erp
  JWT_SECRET_KEY: and0X3NlY3JldF9rZXlfZm9yX2l0ZG9fZXJwX3Byb2R1Y3Rpb25fMjAyNQ==  # jwt_secret_key_for_itdo_erp_production_2025
  
  # OAuth/OIDC Keycloak
  KEYCLOAK_CLIENT_ID: aXRkby1lcnAtcHJvZA==  # itdo-erp-prod
  KEYCLOAK_CLIENT_SECRET: a2V5Y2xvYWtfY2xpZW50X3NlY3JldF9wcm9kdWN0aW9uXzIwMjU=  # keycloak_client_secret_production_2025
  
  # Email Service
  SMTP_PASSWORD: ZW1haWxfc2VydmljZV9wYXNzd29yZF8yMDI1  # email_service_password_2025
  
  # File Storage (AWS S3/MinIO)
  AWS_ACCESS_KEY_ID: QUtJQUlPU0ZPRE5ON0VYQU1QTEU=  # AKIAIOSFODNN7EXAMPLE
  AWS_SECRET_ACCESS_KEY: d0phbHJYVXRuRkVNSS9LN01ERU5HL2JQeFJmaUNZRVhBTVBMRUtFWQ==  # wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  
  # Monitoring
  GRAFANA_ADMIN_PASSWORD: Z3JhZmFuYV9hZG1pbl9zZWN1cmVfMjAyNQ==  # grafana_admin_secure_2025

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: itdo-erp-data
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: database
type: Opaque
data:
  POSTGRES_USER: aXRkb19lcnBfdXNlcg==  # itdo_erp_user
  POSTGRES_PASSWORD: c3VwZXJfc2VjdXJlX3Bhc3N3b3JkXzIwMjU=  # super_secure_password_2025
  POSTGRES_DB: aXRkb19lcnBfcHJvZA==  # itdo_erp_prod
  POSTGRES_REPLICATION_USER: cmVwbGljYXRvcg==  # replicator
  POSTGRES_REPLICATION_PASSWORD: cmVwbGljYXRvcl9wYXNzd29yZF8yMDI1  # replicator_password_2025

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: itdo-erp-data
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
type: Opaque
data:
  REDIS_PASSWORD: cmVkaXNfc2VjdXJlX3Bhc3N3b3JkXzIwMjU=  # redis_secure_password_2025

---
# TLS Certificate Secret Template
apiVersion: v1
kind: Secret
metadata:
  name: itdo-erp-tls
  namespace: itdo-erp-prod
  labels:
    app.kubernetes.io/name: itdo-erp
    app.kubernetes.io/component: tls
type: kubernetes.io/tls
data:
  # These should be replaced with actual certificate data
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t  # Base64 encoded certificate
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t  # Base64 encoded private key

---
# Monitoring Secrets
apiVersion: v1
kind: Secret 
metadata:
  name: monitoring-secrets
  namespace: itdo-erp-monitoring
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/component: observability
type: Opaque
data:
  GRAFANA_ADMIN_USER: YWRtaW4=  # admin
  GRAFANA_ADMIN_PASSWORD: Z3JhZmFuYV9hZG1pbl9zZWN1cmVfMjAyNQ==  # grafana_admin_secure_2025
  PROMETHEUS_ALERT_MANAGER_PASSWORD: YWxlcnRfbWFuYWdlcl9wYXNzd29yZF8yMDI1  # alert_manager_password_2025