# ITDO ERP v2 - Storage Classes for Production
# CC03 v48.0 Business-Aligned Infrastructure

# Fast SSD Storage Class for databases and high-performance workloads
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-ssd
  labels:
    app.kubernetes.io/name: storage
    app.kubernetes.io/component: storage-class
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  type: gp3
  iops: "3000"
  throughput: "125"
  encrypted: "true"
  kmsKeyId: arn:aws:kms:ap-northeast-1:123456789012:key/12345678-1234-1234-1234-123456789012
mountOptions:
- debug

---
# Standard SSD Storage Class for general workloads
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-ssd
  labels:
    app.kubernetes.io/name: storage
    app.kubernetes.io/component: storage-class
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  type: gp3
  iops: "3000"
  throughput: "125"
  encrypted: "true"
mountOptions:
- debug

---
# Standard HDD Storage Class for logs and backups
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  labels:
    app.kubernetes.io/name: storage
    app.kubernetes.io/component: storage-class
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  type: sc1
  encrypted: "true"

---
# High IOPS Storage Class for intensive database workloads
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: high-iops
  labels:
    app.kubernetes.io/name: storage
    app.kubernetes.io/component: storage-class
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  type: io2
  iops: "10000"
  encrypted: "true"
  kmsKeyId: arn:aws:kms:ap-northeast-1:123456789012:key/12345678-1234-1234-1234-123456789012

---
# EFS Storage Class for shared file storage
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-storage
  labels:
    app.kubernetes.io/name: storage
    app.kubernetes.io/component: storage-class
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: efs.csi.aws.com
volumeBindingMode: Immediate
allowVolumeExpansion: false
reclaimPolicy: Retain
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-12345678
  directoryPerms: "0755"
  uid: "1001"
  gid: "1001"

---
# Backup Storage Class for long-term retention
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: backup-storage
  labels:
    app.kubernetes.io/name: storage
    app.kubernetes.io/component: storage-class
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  type: st1
  encrypted: "true"
  kmsKeyId: arn:aws:kms:ap-northeast-1:123456789012:key/12345678-1234-1234-1234-123456789012