# ITDO ERP v2 - Clean Production Alertmanager Configuration
# CC03 v60.0 - Clean Production Implementation

global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@itdo-erp.com'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      continue: true
    
    - match:
        severity: warning
      receiver: 'warning-alerts'

receivers:
  - name: 'default'
    email_configs:
      - to: 'ops-team@itdo-erp.com'
        subject: '[ITDO ERP] Alert: {{ .GroupLabels.alertname }}'
        body: |
          Alert: {{ .GroupLabels.alertname }}
          Severity: {{ .GroupLabels.severity }}
          
          {{ range .Alerts }}
          - Instance: {{ .Labels.instance }}
          - Description: {{ .Annotations.description }}
          {{ end }}

  - name: 'critical-alerts'
    email_configs:
      - to: 'critical-alerts@itdo-erp.com'
        subject: '[CRITICAL] ITDO ERP Alert: {{ .GroupLabels.alertname }}'
        body: |
          🚨 CRITICAL ALERT 🚨
          
          Alert: {{ .GroupLabels.alertname }}
          Environment: Production
          
          {{ range .Alerts }}
          - Instance: {{ .Labels.instance }}
          - Description: {{ .Annotations.description }}
          - Started: {{ .StartsAt }}
          {{ end }}
    
    webhook_configs:
      - url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        send_resolved: true
        title: '🚨 CRITICAL: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          Instance: {{ .Labels.instance }}
          Description: {{ .Annotations.description }}
          {{ end }}

  - name: 'warning-alerts'
    email_configs:
      - to: 'monitoring@itdo-erp.com'
        subject: '[WARNING] ITDO ERP Alert: {{ .GroupLabels.alertname }}'
        body: |
          ⚠️ WARNING ALERT ⚠️
          
          Alert: {{ .GroupLabels.alertname }}
          Environment: Production
          
          {{ range .Alerts }}
          - Instance: {{ .Labels.instance }}
          - Description: {{ .Annotations.description }}
          - Started: {{ .StartsAt }}
          {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']