#!/bin/bash
# Agent Log Collection Script
# Collects activity logs from Claude Code agents and creates GitHub branches

set -e

AGENT_ID="${1:-CC01}"
DATE_STAMP=$(date +%Y%m%d)
LOG_BRANCH="logs/${AGENT_ID}/${DATE_STAMP}"
LOG_DIR="/tmp/claude-code-logs/agent-${AGENT_ID}"

echo "🤖 Agent Log Collector for ${AGENT_ID}"
echo "📅 Date: ${DATE_STAMP}"
echo "🌿 Target Branch: ${LOG_BRANCH}"

# Create log directory if it doesn't exist
mkdir -p "${LOG_DIR}"

# Create log collection file
LOG_FILE="${LOG_DIR}/agent-activity-${DATE_STAMP}.log"

echo "📝 Collecting agent activity logs..."

# Collect system information
{
    echo "=== Agent ${AGENT_ID} Activity Log - ${DATE_STAMP} ==="
    echo "Generated: $(date)"
    echo "Host: $(hostname)"
    echo "User: $(whoami)"
    echo "Working Directory: $(pwd)"
    echo ""
    
    echo "=== Git Status ==="
    git status 2>/dev/null || echo "Not in git repository"
    echo ""
    
    echo "=== Recent Git Commits ==="
    git log --oneline -10 2>/dev/null || echo "No git history available"
    echo ""
    
    echo "=== Environment Variables ==="
    env | grep -E "(CLAUDE|AGENT|CI)" | sort
    echo ""
    
    echo "=== Process List ==="
    ps aux | grep -E "(claude|agent|code)" | head -10
    echo ""
    
    echo "=== File System Activity ==="
    find /home/work/ITDO_ERP2 -type f -name "*.log" -mtime -1 2>/dev/null | head -20
    echo ""
    
    echo "=== Agent Specific Logs ==="
    if [ -f "/tmp/agent-${AGENT_ID}-loop.log" ]; then
        echo "Agent Loop Log (last 50 lines):"
        tail -50 "/tmp/agent-${AGENT_ID}-loop.log"
    else
        echo "No agent loop log found at /tmp/agent-${AGENT_ID}-loop.log"
    fi
    echo ""
    
    if [ -f "/tmp/agent-${AGENT_ID}-loop.db" ]; then
        echo "Agent Database Status:"
        sqlite3 "/tmp/agent-${AGENT_ID}-loop.db" "SELECT COUNT(*) as task_count FROM task_history;" 2>/dev/null || echo "Cannot read database"
    else
        echo "No agent database found at /tmp/agent-${AGENT_ID}-loop.db"
    fi
    echo ""
    
    echo "=== Command History ==="
    if [ -d "${LOG_DIR}" ]; then
        echo "Command logs directory exists: ${LOG_DIR}"
        ls -la "${LOG_DIR}" 2>/dev/null || echo "Cannot list log directory"
    else
        echo "No command logs directory found"
    fi
    echo ""
    
    echo "=== System Resource Usage ==="
    echo "Memory Usage:"
    free -h 2>/dev/null || echo "Memory info not available"
    echo ""
    echo "Disk Usage:"
    df -h /tmp 2>/dev/null || echo "Disk info not available"
    echo ""
    
    echo "=== Network Connectivity ==="
    ping -c 1 github.com 2>/dev/null && echo "GitHub connectivity: OK" || echo "GitHub connectivity: FAILED"
    echo ""
    
    echo "=== Agent Status Summary ==="
    echo "Agent ID: ${AGENT_ID}"
    echo "Collection Time: $(date)"
    echo "Log Branch: ${LOG_BRANCH}"
    echo "Status: Log collection completed successfully"
    
} > "${LOG_FILE}"

echo "✅ Log collection completed: ${LOG_FILE}"

# Create GitHub branch and push logs
echo "🌿 Creating GitHub branch: ${LOG_BRANCH}"

# Create and switch to log branch
git checkout -b "${LOG_BRANCH}" 2>/dev/null || {
    echo "⚠️  Branch ${LOG_BRANCH} already exists, switching to it"
    git checkout "${LOG_BRANCH}"
}

# Create logs directory in repository
mkdir -p "logs/${AGENT_ID}"

# Copy log file to repository
cp "${LOG_FILE}" "logs/${AGENT_ID}/agent-activity-${DATE_STAMP}.log"

# Create summary file
cat > "logs/${AGENT_ID}/collection-summary.md" << EOF
# Agent ${AGENT_ID} Log Collection Summary

**Date**: ${DATE_STAMP}  
**Branch**: ${LOG_BRANCH}  
**Generated**: $(date)

## Files Collected
- \`agent-activity-${DATE_STAMP}.log\` - Complete activity log
- \`collection-summary.md\` - This summary file

## Collection Status
✅ Log collection completed successfully

## Agent Information
- **Agent ID**: ${AGENT_ID}
- **Collection Time**: $(date)
- **Host**: $(hostname)
- **Working Directory**: $(pwd)

## Next Steps
1. Review the activity log for agent behavior analysis
2. Check for any issues or errors in the logs
3. Use findings to improve agent coordination

---
🤖 Generated by agent-log-collector.sh
EOF

# Add and commit files
git add "logs/${AGENT_ID}/"
git commit -m "📊 Add ${AGENT_ID} activity logs for ${DATE_STAMP}

- Agent activity log collection
- System status and environment info
- Command history and resource usage
- Generated for issue diagnostic purposes

🤖 Auto-generated by agent-log-collector.sh"

# Push to remote
echo "📤 Pushing logs to remote repository..."
git push -u origin "${LOG_BRANCH}"

echo ""
echo "✅ Agent log collection completed successfully!"
echo "📊 Branch: ${LOG_BRANCH}"
echo "📁 Files: logs/${AGENT_ID}/agent-activity-${DATE_STAMP}.log"
echo "🔗 View on GitHub: https://github.com/itdojp/ITDO_ERP2/tree/${LOG_BRANCH}"
echo ""
echo "🎯 Ready for GitHub issue update:"
echo "   Issue #324, #325, #326, or #327 depending on agent"