{{- if and .Values.monitoring.enabled .Values.monitoring.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "backend-api.fullname" . }}
  namespace: {{ .Values.monitoring.prometheusRule.namespace }}
  labels:
    {{- include "backend-api.labels" . | nindent 4 }}
spec:
  groups:
  - name: backend-api.rules
    rules:
    - alert: BackendAPIHighErrorRate
      expr: |
        (
          rate(backend_api_http_requests_total{status=~"5.."}[5m]) /
          rate(backend_api_http_requests_total[5m])
        ) > 0.05
      for: 5m
      labels:
        severity: warning
        service: backend-api
      annotations:
        summary: "High error rate detected for Backend API"
        description: "Backend API error rate is {{ $value | humanizePercentage }} which is above the 5% threshold"
        
    - alert: BackendAPIHighLatency
      expr: |
        histogram_quantile(0.95, 
          rate(backend_api_http_request_duration_seconds_bucket[5m])
        ) > 2
      for: 5m
      labels:
        severity: warning
        service: backend-api
      annotations:
        summary: "High latency detected for Backend API"
        description: "Backend API 95th percentile latency is {{ $value }}s which is above the 2s threshold"
        
    - alert: BackendAPILowThroughput
      expr: |
        rate(backend_api_http_requests_total[5m]) < 1
      for: 10m
      labels:
        severity: warning
        service: backend-api
      annotations:
        summary: "Low throughput detected for Backend API"
        description: "Backend API throughput is {{ $value }} requests/second which is below the 1 req/s threshold"
        
    - alert: BackendAPIPodCrashLooping
      expr: |
        rate(kube_pod_container_status_restarts_total{pod=~"{{ include "backend-api.fullname" . }}-.*"}[15m]) > 0
      for: 0m
      labels:
        severity: critical
        service: backend-api
      annotations:
        summary: "Backend API pod is crash looping"
        description: "Pod {{ $labels.pod }} is restarting frequently"
        
    - alert: BackendAPIHighMemoryUsage
      expr: |
        (
          container_memory_working_set_bytes{pod=~"{{ include "backend-api.fullname" . }}-.*"} /
          container_spec_memory_limit_bytes{pod=~"{{ include "backend-api.fullname" . }}-.*"}
        ) > 0.8
      for: 10m
      labels:
        severity: warning
        service: backend-api
      annotations:
        summary: "High memory usage for Backend API"
        description: "Pod {{ $labels.pod }} memory usage is {{ $value | humanizePercentage }}"
        
    - alert: BackendAPIHighCPUUsage
      expr: |
        (
          rate(container_cpu_usage_seconds_total{pod=~"{{ include "backend-api.fullname" . }}-.*"}[5m]) /
          container_spec_cpu_quota{pod=~"{{ include "backend-api.fullname" . }}-.*"} * 100000
        ) > 80
      for: 10m
      labels:
        severity: warning
        service: backend-api
      annotations:
        summary: "High CPU usage for Backend API"
        description: "Pod {{ $labels.pod }} CPU usage is {{ $value }}%"
{{- end }}