{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend-api.fullname" . }}-secret
  labels:
    {{- include "backend-api.labels" . | nindent 4 }}
type: Opaque
data:
  database-password: {{ .Values.secrets.databasePassword | b64enc | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  encryption-key: {{ .Values.secrets.encryptionKey | b64enc | quote }}
{{- end }}