"""Interface definitions for service integration."""

from app.interfaces.organization_interface import (
    DepartmentCreatedEvent,
    DepartmentDeletedEvent,
    DepartmentIntegrationMixin,
    OrganizationActivatedEvent,
    OrganizationConstraints,
    OrganizationDeactivatedEvent,
    OrganizationDeletedEvent,
    OrganizationEvent,
    OrganizationInfo,
    OrganizationServiceInterface,
    OrganizationSettingsUpdatedEvent,
    OrganizationStructureChangedEvent,
)
from app.interfaces.role_interface import (
    PermissionChangedEvent,
    PermissionEffect,
    PermissionInfo,
    PermissionScope,
    PermissionValidationMixin,
    RoleAssignedEvent,
    RoleAssignment,
    RoleCreatedEvent,
    RoleDeletedEvent,
    RoleEvent,
    RoleInfo,
    RoleRevokedEvent,
    RoleServiceInterface,
    RoleType,
    SystemPermissions,
    SystemRoles,
)

__all__ = [
    # Organization interfaces
    "OrganizationServiceInterface",
    "DepartmentIntegrationMixin",
    "OrganizationInfo",
    "OrganizationConstraints",
    "OrganizationEvent",
    "OrganizationActivatedEvent",
    "OrganizationDeactivatedEvent",
    "OrganizationDeletedEvent",
    "OrganizationSettingsUpdatedEvent",
    "DepartmentCreatedEvent",
    "DepartmentDeletedEvent",
    "OrganizationStructureChangedEvent",
    # Role interfaces
    "RoleServiceInterface",
    "PermissionValidationMixin",
    "RoleInfo",
    "PermissionInfo",
    "RoleAssignment",
    "PermissionScope",
    "RoleType",
    "PermissionEffect",
    "SystemRoles",
    "SystemPermissions",
    "RoleEvent",
    "RoleAssignedEvent",
    "RoleRevokedEvent",
    "RoleCreatedEvent",
    "RoleDeletedEvent",
    "PermissionChangedEvent",
]
