apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - postgres-statefulset.yaml
  - redis-deployment.yaml
  - ingress.yaml

configMapGenerator:
  - name: app-config
    files:
      - config.json

secretGenerator:
  - name: app-secrets
    envs:
      - secrets.env