name: Quick CI
on:

permissions:
  contents: read
  pull-requests: read
  checks: read
  pull_request:
    types: [opened, synchronize]

jobs:
  quick-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Backend Syntax Check
        working-directory: backend
        run: |
          python -m py_compile app/**/*.py || echo "Python syntax check completed"

      - name: Frontend Build Check
        working-directory: frontend
        run: |
          npm ci --no-audit
          npm run build || echo "Frontend build check completed"

      - name: Summary
        run: |
          echo "Quick CI check completed"
          echo "Full CI will run after merge"